#!/usr/bin/env -S uv run --script
#
# /// script
# requires-python = ">=3.14"
# dependencies = []
# ///

import os
import re
import subprocess
import sys
from pathlib import Path
from argparse import ArgumentParser
from typing import List, Dict, Set, Tuple, Optional, Any
import json
from dataclasses import dataclass, field, asdict
from concurrent.futures import as_completed, ThreadPoolExecutor
import hashlib
import shlex

ERRORS_CACHE_FOLDER = Path(".ronin/c_cpp_compile_errors")
ERRORS_STATE_FILE   = ERRORS_CACHE_FOLDER / "state.json"

# Matches: #include "/absolute/path/to/file.cpp"  (CMake Unity build includes)
UNITY_INCLUDE_RE = re.compile(r'^#include\s+"([^"]+\.(?:cpp|cxx|cc|c))"', re.MULTILINE)

type ContentHash = str
type PathHash = str

@dataclass
class CompileCommand:
    file: str
    command: List[str]
    unity_sources: List[str] = field(default_factory=list)
    path_hash: PathHash = field(init=False)
    content_hash: ContentHash = field(init=False)

    def __post_init__(self):
        self.path_hash = get_file_hash(self.file)
        # For Unity builds hash the real source files, not the generated wrapper —
        # the wrapper never changes but its included sources do.
        sources = self.unity_sources if self.unity_sources else [self.file]
        self.content_hash = get_combined_content_hash(sources)

@dataclass
class TargetFile:
    header_deps: Set[str]
    content_hash: ContentHash
    path_hash: PathHash

@dataclass
class State:
    targets: Dict[str, TargetFile]
    unique_deps: Dict[str, ContentHash]

    @staticmethod
    def from_dict(data: Dict) -> "State":
        targets = {
            k: TargetFile(**v) for k, v in data.get("targets", {}).items()
        }
        for t in targets.values():
            t.header_deps = set(t.header_deps)
        return State(targets=targets, unique_deps=data.get("unique_deps", {}))

def parse_unity_sources(file: str) -> List[str]:
    """Return the list of .cpp/.cxx source files included by a CMake Unity build file."""
    try:
        with open(file, "r", encoding="utf8") as f:
            header = f.read(64)
            if "generated by CMake" not in header:
                return []
            content = header + f.read()
        return UNITY_INCLUDE_RE.findall(content)
    except (OSError, UnicodeDecodeError):
        return []

def extract_command(cmd_entry: Dict) -> List[str]:
    """Prefer 'arguments' array over 'command' string to bypass shlex.split"""
    if "arguments" in cmd_entry:
        parts = cmd_entry["arguments"][:]
    else:
        parts = shlex.split(cmd_entry.get("command", ""))
    
    if "-o" in parts:
        idx = parts.index("-o")
        parts = parts[:idx] + parts[idx+2:]
        
    # Strip existing diagnostics formatting flags so we can dynamically inject the right one
    parts = [p for p in parts if not p.startswith("-fdiagnostics-format=")]
    return parts

def get_commands_of_interest(compile_commands_path: str, path_prefix: str, 
                             cxx: Optional[str], cc: Optional[str],
                             analysis_flags: List[str]) -> Dict[str, CompileCommand]:
    prefix = Path(path_prefix)
    with open(compile_commands_path, "r", encoding="utf8") as infile:
        commands = json.load(infile)
    out = {}
    for c in commands:
        file = Path(c["file"])
        if not file.exists():
            continue

        unity_sources = parse_unity_sources(c["file"])

        if unity_sources:
            if not any(Path(s).is_relative_to(prefix) for s in unity_sources):
                continue
        else:
            if not file.is_relative_to(prefix):
                continue

        cmd = CompileCommand(
            file=c["file"],
            command=extract_command(c),
            unity_sources=unity_sources,
        )
        cmd.command.extend(analysis_flags)
        
        # Determine language by file extension (.c is C, others are C++)
        is_c_file = file.suffix == ".c"
        
        if is_c_file and cc is not None:
            cmd.command[0] = cc
        elif not is_c_file and cxx is not None:
            cmd.command[0] = cxx
            
        out[c["file"]] = cmd
    return out

def get_file_hash(file: str) -> str:
    h = hashlib.new("sha1")
    h.update(file.encode())
    return h.hexdigest()

def get_file_content_hash(file: str) -> str:
    """Use C-optimized hashlib.file_digest"""
    try:
        with open(file, "rb") as f:
            return hashlib.file_digest(f, "blake2b").hexdigest()
    except OSError:
        return ""

def get_combined_content_hash(files: List[str]) -> str:
    """Hash the contents of one or more files into a single digest using C-optimized paths."""
    h = hashlib.blake2b()
    for file in sorted(files):
        try:
            with open(file, "rb") as f:
                file_h = hashlib.file_digest(f, "blake2b")
                h.update(file_h.digest())
        except OSError:
            pass
    return h.hexdigest()

def read_cache(cmd: CompileCommand, cached_deps: Set[str]) -> Tuple[Set[str], Set[str]]:
    cache_file = ERRORS_CACHE_FOLDER / f"{cmd.path_hash}.errors"
    if not cache_file.exists():
        return set(), cached_deps
    with open(cache_file, "r", encoding="utf8") as infile:
        return set(infile.readlines()), cached_deps

def parse_clang_sarif(diagnostics: dict) -> Set[str]:
    """Flattens and parses Clang's SARIF JSON output."""
    errors = set()
    results = (
        res for run in diagnostics.get("runs", [])
        for res in run.get("results", [])
        if res.get("level") == "error"
    )
    
    for result in results:
        message = result.get("message", {}).get("text", "").replace("\n", " ")
        for loc in result.get("locations", []):
            phys_loc = loc.get("physicalLocation", {})
            file_uri = phys_loc.get("artifactLocation", {}).get("uri", "<unknown>")
            file_path = file_uri.replace("file://", "")
            
            region = phys_loc.get("region", {})
            line = region.get("startLine", 0)
            col = region.get("startColumn", 0)
            errors.add(f"{file_path}:{line}:{col}:{message}\n")
            
    return errors

def parse_gcc_json(diagnostics: Any) -> Set[str]:
    """Flattens and parses GCC's custom JSON output."""
    errors = set()
    diags_list = diagnostics if isinstance(diagnostics, list) else [diagnostics]
    
    diags = (d for d in diags_list if d.get("kind") == "error")
    
    for diag in diags:
        message = diag.get("message", "").replace("\n", " ")
        for loc in diag.get("locations", []):
            caret = loc.get("caret", {})
            file_path = caret.get("file", "<unknown>")
            line = caret.get("line", 0)
            col = caret.get("column", 0)
            errors.add(f"{file_path}:{line}:{col}:{message}\n")
            
    return errors

def parse_dependency_file(d_file: Path, prefix_path: Path) -> Set[str]:
    """Reads a .d file and returns resolved dependencies within the prefix path."""
    if not d_file.exists():
        return set()
        
    try:
        content = d_file.read_text(encoding="utf8").replace("\\\n", "")
        parts = shlex.split(content)
        if len(parts) <= 1:
            return set()
            
        # parts[0] is the target (e.g., 'main.o:'), parts[1:] are the headers
        paths = (Path(d).resolve() for d in parts[1:])
        return {str(p) for p in paths if p.is_relative_to(prefix_path)}
    except Exception:
        return set()

def run_cmd(cmd: CompileCommand, prefix_path: Path) -> Tuple[Set[str], Set[str]]:
    """Compile and discover dependencies in the same pass using -MMD"""
    cache_file = ERRORS_CACHE_FOLDER / f"{cmd.path_hash}.errors"
    d_file = ERRORS_CACHE_FOLDER / f"{cmd.path_hash}.d"
    
    # Determine which compiler we are invoking
    is_clang = "clang" in Path(cmd.command[0]).name.lower()

    # Inject the correct JSON schema flag
    diag_flag = "-fdiagnostics-format=sarif" if is_clang else "-fdiagnostics-format=json"
    full_cmd = cmd.command + ["-MMD", "-MF", str(d_file), diag_flag]
    
    process = subprocess.Popen(full_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    _, stderr_data = process.communicate()

    # 1. Parse errors
    errors = set()
    if stderr_data:
        try:
            diagnostics = json.loads(stderr_data)
            errors = parse_clang_sarif(diagnostics) if is_clang else parse_gcc_json(diagnostics)
        except json.JSONDecodeError:
            pass

    with open(cache_file, "w", encoding="utf8") as outfile:
        outfile.writelines(errors)

    # 2. Parse newly generated dependencies (.d file)
    filtered_deps = parse_dependency_file(d_file, prefix_path)

    return errors, filtered_deps

def load_or_initialize_state(ignore_cache: bool = False) -> State:
    if (not ignore_cache) and ERRORS_STATE_FILE.exists():
        with open(ERRORS_STATE_FILE, "r", encoding="utf8") as infile:
            try:
                return State.from_dict(json.load(infile))
            except json.JSONDecodeError:
                pass
    return State(targets={}, unique_deps={})

def get_needs_recompile(cmds: Dict[str, CompileCommand], state: State) -> Tuple[Set[str], Set[str], Dict[str, str]]:
    """Determine which targets need recompilation using purely state and content hashes."""
    changed_files = set()
    unchanged_files = set()
    header_hash_cache = {}
    
    for k, cmd in cmds.items():
        if k not in state.targets:
            changed_files.add(k)
            continue
            
        target = state.targets[k]
        
        # Check if the source file itself changed
        if target.content_hash != cmd.content_hash:
            changed_files.add(k)
            continue
            
        # Check if any known header dependencies changed or were deleted
        deps_changed = False
        for dep in target.header_deps:
            if not os.path.exists(dep):
                deps_changed = True
                break
                
            if dep not in header_hash_cache:
                header_hash_cache[dep] = get_file_content_hash(dep)
                
            if header_hash_cache[dep] != state.unique_deps.get(dep):
                deps_changed = True
                break
                
        if deps_changed:
            changed_files.add(k)
        else:
            unchanged_files.add(k)
            
    return changed_files, unchanged_files, header_hash_cache

def json_set_to_list(obj):
    if isinstance(obj, set):
        return list(obj)
    raise TypeError

if __name__ == "__main__":
    parser = ArgumentParser(description="Parse compile_commands.json and report compiler errors")
    parser.add_argument("--compile-commands", help="Path to compile_commands.json", type=str, required=True, dest="compile_commands")
    parser.add_argument("--path-prefix", help="Only analyze files that has this path prefix", type=str, required=True, dest="path_prefix")
    parser.add_argument("--cxx", help="Use this C++ compiler instead of default specified in compile_commands.json",
                        type=str, required=False, default=None, dest="cxx")
    parser.add_argument("--cc", help="Use this C compiler instead of default specified in compile_commands.json",
                        type=str, required=False, default=None, dest="cc")
    parser.add_argument("-j", "--jobs", help="Number threads to use", type=int, required=False, default=4, dest="jobs")
    parser.add_argument("--no-cache", help="Ignore caching and perform analysis from scratch",
                        action="store_true", required=False, dest="no_cache")
    parser.add_argument("--analysis-flags", help="Comma separated analysis flags to use",
                        type=lambda s: s.split(","), required=False, default=["-fsyntax-only"],
                        dest="analysis_flags")

    args, _ = parser.parse_known_args()

    if not Path(args.compile_commands).exists():
        print(f"[ERROR] File {args.compile_commands} do not exist")
        sys.exit(1)
        
    ERRORS_CACHE_FOLDER.mkdir(exist_ok=True)
    resolved_prefix = Path(args.path_prefix).resolve()

    state = load_or_initialize_state(args.no_cache)
    cmds = get_commands_of_interest(args.compile_commands, args.path_prefix, args.cxx, args.cc, args.analysis_flags)
    
    # 1. Determine exactly what needs recompilation
    changed_files, unchanged_files, header_hash_cache = get_needs_recompile(cmds, state)

    # 2. Dispatch tasks to thread pool
    executor = ThreadPoolExecutor(max_workers=args.jobs)
    futures = { **{executor.submit(run_cmd, cmds[f], resolved_prefix): f for f in changed_files},
                **{executor.submit(read_cache, cmds[f], state.targets[f].header_deps): f for f in unchanged_files} }

    for future in as_completed(futures):
        file = futures[future]

        if file not in state.targets:
            state.targets[file] = TargetFile(set(), "", "")
            
        try:
            errors, file_deps = future.result()
            state.targets[file].header_deps = file_deps
            state.targets[file].content_hash = cmds[file].content_hash
            state.targets[file].path_hash = cmds[file].path_hash
            
            if errors:
                print(''.join(errors).rstrip('\n'))
        except Exception as e:
            print(f"[ERROR] {e}", file=sys.stderr)

    executor.shutdown()

    # 3. Update cached dependencies & Save State
    if not args.no_cache:
        new_unique_deps = {}
        # Only preserve the dependencies actively used by the current targets
        for target in state.targets.values():
            for dep in target.header_deps:
                if dep not in new_unique_deps:
                    if dep not in header_hash_cache:
                        header_hash_cache[dep] = get_file_content_hash(dep)
                    new_unique_deps[dep] = header_hash_cache[dep]
                    
        state.unique_deps = new_unique_deps
        
        with open(ERRORS_STATE_FILE, "w", encoding="utf8") as outfile:
            state_dict = asdict(state)
            json.dump(state_dict, outfile, indent=2, default=json_set_to_list)
