#!/usr/bin/env -S uv run --script
#
# /// script
# requires-python = ">=3.14"
# dependencies = []
# ///

import os
import re
import shutil
import signal
import subprocess
import sys
from pathlib import Path
from argparse import ArgumentParser
from typing import List, Dict, Set, Tuple, Optional, Any
import json
from dataclasses import dataclass, field, asdict
from concurrent.futures import as_completed, ThreadPoolExecutor
import hashlib
import shlex

ERRORS_CACHE_FOLDER = Path(".ronin/c_cpp_compile_errors")
ERRORS_STATE_FILE   = ERRORS_CACHE_FOLDER / "state.json"

COMPILE_TIMEOUT_S = 300

COMPILER_LAUNCHERS = frozenset({"ccache", "sccache", "distcc", "icecc", "icerun",
                                "buildcache", "gomacc"})

# Matches: #include "/absolute/path/to/file.cpp"  (CMake Unity build includes)
UNITY_INCLUDE_RE = re.compile(r'^#include\s+"([^"]+\.(?:cpp|cxx|cc|c))"', re.MULTILINE)

type ContentHash = str
type PathHash = str

@dataclass
class CompileCommand:
    file: str
    command: List[str]
    unity_sources: List[str] = field(default_factory=list)
    path_hash: PathHash = field(init=False)
    content_hash: ContentHash = ""

    def __post_init__(self):
        self.path_hash = get_file_hash(self.file)

    @property
    def sources(self) -> List[str]:
        """What to hash: for a Unity build the real sources, not the generated
        wrapper, which never changes while its includes do."""
        return self.unity_sources if self.unity_sources else [self.file]

@dataclass
class TargetFile:
    header_deps: Set[str]
    content_hash: ContentHash
    path_hash: PathHash

@dataclass
class State:
    targets: Dict[str, TargetFile]
    unique_deps: Dict[str, ContentHash]

    @staticmethod
    def from_dict(data: Dict) -> "State":
        targets = {
            k: TargetFile(**v) for k, v in data.get("targets", {}).items()
        }
        for t in targets.values():
            t.header_deps = set(t.header_deps)
        return State(targets=targets, unique_deps=data.get("unique_deps", {}))

def parse_unity_sources(file: str) -> List[str]:
    """Return the list of .cpp/.cxx source files included by a CMake Unity build file."""
    try:
        with open(file, "r", encoding="utf8") as f:
            header = f.read(64)
            if "generated by CMake" not in header:
                return []
            content = header + f.read()
        return UNITY_INCLUDE_RE.findall(content)
    except (OSError, UnicodeDecodeError):
        return []

def extract_command(cmd_entry: Dict) -> List[str]:
    """Prefer 'arguments' array over 'command' string to bypass shlex.split"""
    if "arguments" in cmd_entry:
        parts = cmd_entry["arguments"][:]
    else:
        parts = shlex.split(cmd_entry.get("command", ""))
    
    if "-o" in parts:
        idx = parts.index("-o")
        parts = parts[:idx] + parts[idx+2:]
        
    # Strip existing diagnostics formatting flags so we can dynamically inject the right one
    parts = [p for p in parts if not p.startswith("-fdiagnostics-format=")]
    return parts

def split_compiler(command: List[str]) -> Tuple[List[str], List[str]]:
    """Split a command into (compiler words, everything after it).

    The compiler is argv[0], plus whatever follows while argv[0] keeps being a launcher:
    `ccache g++ -c x.cpp` gives (["ccache", "g++"], ["-c", "x.cpp"]).
    """
    end = 1
    while end < len(command) and Path(command[end - 1]).name.lower() in COMPILER_LAUNCHERS:
        end += 1
    return command[:end], command[end:]


def replace_compiler(command: List[str], replacement: str) -> List[str]:
    """Swap the compiler in `command` for `replacement`, which may be several words.

    A compiler is often not one path: "ccache g++", "sccache clang++ --target=arm64", or
    a path with a space in it. The command is executed as an argv list and never through
    a shell, so the replacement is split the way a shell would -- quote it if it
    contains spaces that belong together ("'/opt/my tools/g++'").

    The whole compiler is replaced, launcher included, because that is what
    compile_commands.json specified as the compiler. To keep a launcher, name it:
    --cxx "ccache clang++".
    """
    words = shlex.split(replacement)
    if not words:
        return command
    return words + split_compiler(command)[1]


def is_clang_compiler(command: List[str]) -> bool:
    """Whether this command runs clang, looking past any launcher in front of it."""
    return any("clang" in Path(word).name.lower() for word in split_compiler(command)[0])


def get_commands_of_interest(compile_commands_path: str, path_prefix: str,
                             cxx: Optional[str], cc: Optional[str],
                             analysis_flags: List[str]) -> Dict[str, CompileCommand]:
    prefix = Path(path_prefix)
    with open(compile_commands_path, "r", encoding="utf8") as infile:
        commands = json.load(infile)
    out = {}
    for c in commands:
        file = Path(c["file"])
        if not file.exists():
            continue

        unity_sources = parse_unity_sources(c["file"])

        if unity_sources:
            if not any(Path(s).is_relative_to(prefix) for s in unity_sources):
                continue
        else:
            if not file.is_relative_to(prefix):
                continue

        cmd = CompileCommand(
            file=c["file"],
            command=extract_command(c),
            unity_sources=unity_sources,
        )
        cmd.command.extend(analysis_flags)

        # Language by file extension: .c is C, everything else C++.
        replacement = cc if file.suffix == ".c" else cxx
        if replacement:
            cmd.command = replace_compiler(cmd.command, replacement)

        out[c["file"]] = cmd
    return out

def get_file_hash(file: str) -> str:
    return hashlib.blake2b(file.encode(), digest_size=16).hexdigest()

def get_file_content_hash(file: str) -> str:
    try:
        with open(file, "rb") as f:
            return hashlib.file_digest(f, "blake2b").hexdigest()
    except OSError:
        return ""

def get_combined_content_hash(files: List[str]) -> str:
    h = hashlib.blake2b()
    for file in sorted(files):
        try:
            with open(file, "rb") as f:
                file_h = hashlib.file_digest(f, "blake2b")
                h.update(file_h.digest())
        except OSError:
            pass
    return h.hexdigest()

def hash_sources(cmds: Dict[str, CompileCommand], pool: ThreadPoolExecutor) -> None:
    """Fill in every command's content hash, in parallel.

    Reading and digesting thousands of files is I/O bound and hashlib drops the GIL,
    so the pool that runs the compilers is the right place for it too.
    """
    targets = list(cmds.values())
    for cmd, digest in zip(targets, pool.map(get_combined_content_hash,
                                             (c.sources for c in targets))):
        cmd.content_hash = digest


def prime_header_hashes(state: State, pool: ThreadPoolExecutor) -> Dict[str, str]:
    """Hash last run's known headers up front, in parallel.

    get_needs_recompile stops at the first changed dependency, so on a tree where
    little moved it ends up hashing nearly every header anyway -- one parallel pass is
    the same work without the wait. On a first run there is no previous state, so this
    costs nothing.
    """
    deps = sorted({dep for target in state.targets.values() for dep in target.header_deps
                   if os.path.exists(dep)})
    return dict(zip(deps, pool.map(get_file_content_hash, deps)))


def read_cache(cmd: CompileCommand, cached_deps: Set[str]) -> Tuple[Set[str], Set[str]]:
    cache_file = ERRORS_CACHE_FOLDER / f"{cmd.path_hash}.errors"
    if not cache_file.exists():
        return set(), cached_deps
    with open(cache_file, "r", encoding="utf8") as infile:
        return set(infile.readlines()), cached_deps

def parse_clang_sarif(diagnostics: dict) -> Set[str]:
    """Flattens and parses Clang's SARIF JSON output."""
    errors = set()
    results = (
        res for run in diagnostics.get("runs", [])
        for res in run.get("results", [])
        if res.get("level") == "error"
    )
    
    for result in results:
        message = result.get("message", {}).get("text", "").replace("\n", " ")
        for loc in result.get("locations", []):
            phys_loc = loc.get("physicalLocation", {})
            file_uri = phys_loc.get("artifactLocation", {}).get("uri", "<unknown>")
            file_path = file_uri.replace("file://", "")
            
            region = phys_loc.get("region", {})
            line = region.get("startLine", 0)
            col = region.get("startColumn", 0)
            errors.add(f"{file_path}:{line}:{col}:{message}\n")
            
    return errors

def parse_gcc_json(diagnostics: Any) -> Set[str]:
    """Flattens and parses GCC's custom JSON output."""
    errors = set()
    diags_list = diagnostics if isinstance(diagnostics, list) else [diagnostics]
    
    diags = (d for d in diags_list if d.get("kind") == "error")
    
    for diag in diags:
        message = diag.get("message", "").replace("\n", " ")
        for loc in diag.get("locations", []):
            caret = loc.get("caret", {})
            file_path = caret.get("file", "<unknown>")
            line = caret.get("line", 0)
            col = caret.get("column", 0)
            errors.add(f"{file_path}:{line}:{col}:{message}\n")
            
    return errors

def parse_dependency_file(d_file: Path, prefix_path: Path) -> Set[str]:
    """Reads a .d file and returns resolved dependencies within the prefix path."""
    if not d_file.exists():
        return set()
        
    try:
        content = d_file.read_text(encoding="utf8").replace("\\\n", "")
        parts = shlex.split(content)
        if len(parts) <= 1:
            return set()
            
        # parts[0] is the target (e.g., 'main.o:'), parts[1:] are the headers
        paths = (Path(d).resolve() for d in parts[1:])
        return {str(p) for p in paths if p.is_relative_to(prefix_path)}
    except Exception:
        return set()

def run_cmd(cmd: CompileCommand, prefix_path: Path) -> Tuple[Set[str], Set[str]]:
    """Compile and discover dependencies in the same pass using -MMD"""
    cache_file = ERRORS_CACHE_FOLDER / f"{cmd.path_hash}.errors"
    d_file = ERRORS_CACHE_FOLDER / f"{cmd.path_hash}.d"
    
    # Determine which compiler we are invoking
    is_clang = is_clang_compiler(cmd.command)

    # Inject the correct JSON schema flag
    diag_flag = "-fdiagnostics-format=sarif" if is_clang else "-fdiagnostics-format=json"
    full_cmd = cmd.command + ["-MMD", "-MF", str(d_file), diag_flag]

    # Its own session, so a timeout can take the whole tree down: a compiler driver
    # spawns cc1/ld of its own, and killing only the process we forked leaves those
    # running with nobody waiting on them.
    with subprocess.Popen(full_cmd, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE,
                          text=True, start_new_session=True) as process:
        try:
            _, stderr_data = process.communicate(timeout=COMPILE_TIMEOUT_S)
        except subprocess.TimeoutExpired:
            os.killpg(process.pid, signal.SIGKILL)  # session leader, so pid == pgid
            process.communicate()
            # Raised, not swallowed: the caller records a result only for targets that
            # finished, so a timed-out file stays "changed" and is retried next run.
            raise RuntimeError(f"timed out after {COMPILE_TIMEOUT_S}s: {cmd.file}") from None

    # 1. Parse errors
    errors = set()
    if stderr_data:
        try:
            diagnostics = json.loads(stderr_data)
            errors = parse_clang_sarif(diagnostics) if is_clang else parse_gcc_json(diagnostics)
        except json.JSONDecodeError:
            pass

    with open(cache_file, "w", encoding="utf8") as outfile:
        outfile.writelines(errors)

    # 2. Parse newly generated dependencies (.d file)
    filtered_deps = parse_dependency_file(d_file, prefix_path)

    return errors, filtered_deps

def load_or_initialize_state(ignore_cache: bool = False) -> State:
    """Last run's state, or an empty one.

    Anything unreadable is treated as absent rather than fatal -- a truncated file, or
    one written by an older schema, costs a full re-analysis and nothing worse.
    """
    if (not ignore_cache) and ERRORS_STATE_FILE.exists():
        try:
            with open(ERRORS_STATE_FILE, "r", encoding="utf8") as infile:
                return State.from_dict(json.load(infile))
        except (json.JSONDecodeError, OSError, TypeError, KeyError, AttributeError):
            pass
    return State(targets={}, unique_deps={})


def save_state(state: State) -> None:
    """Write the state file atomically, so an interrupted run cannot truncate it."""
    tmp = ERRORS_STATE_FILE.with_suffix(".json.tmp")
    with open(tmp, "w", encoding="utf8") as outfile:
        json.dump(asdict(state), outfile, indent=2, default=json_set_to_list)
    os.replace(tmp, ERRORS_STATE_FILE)

def get_needs_recompile(cmds: Dict[str, CompileCommand], state: State,
                        header_hash_cache: Dict[str, str]) -> Tuple[Set[str], Set[str], Dict[str, str]]:
    """Determine which targets need recompilation using purely state and content hashes.

    `header_hash_cache` comes in warm from prime_header_hashes and is filled in for
    anything it missed, so the caller can reuse it when rewriting unique_deps.
    """
    changed_files = set()
    unchanged_files = set()

    for k, cmd in cmds.items():
        if k not in state.targets:
            changed_files.add(k)
            continue
            
        target = state.targets[k]
        
        # Check if the source file itself changed
        if target.content_hash != cmd.content_hash:
            changed_files.add(k)
            continue
            
        # Check if any known header dependencies changed or were deleted
        deps_changed = False
        for dep in target.header_deps:
            if not os.path.exists(dep):
                deps_changed = True
                break
                
            if dep not in header_hash_cache:
                header_hash_cache[dep] = get_file_content_hash(dep)
                
            if header_hash_cache[dep] != state.unique_deps.get(dep):
                deps_changed = True
                break
                
        if deps_changed:
            changed_files.add(k)
        else:
            unchanged_files.add(k)
            
    return changed_files, unchanged_files, header_hash_cache

def json_set_to_list(obj):
    if isinstance(obj, set):
        return list(obj)
    raise TypeError

if __name__ == "__main__":
    parser = ArgumentParser(description="Parse compile_commands.json and report compiler errors")
    parser.add_argument("--compile-commands", help="Path to compile_commands.json", type=str, required=True, dest="compile_commands")
    parser.add_argument("--path-prefix", help="Only analyze files that has this path prefix", type=str, required=True, dest="path_prefix")
    parser.add_argument("--cxx", help="Use this C++ compiler instead of default specified in compile_commands.json",
                        type=str, required=False, default=None, dest="cxx")
    parser.add_argument("--cc", help="Use this C compiler instead of default specified in compile_commands.json",
                        type=str, required=False, default=None, dest="cc")
    parser.add_argument("-j", "--jobs", help="Number threads to use", type=int, required=False,
                        default=os.cpu_count() or 4, dest="jobs")
    parser.add_argument("--no-cache", help="Ignore caching and perform analysis from scratch",
                        action="store_true", required=False, dest="no_cache")
    parser.add_argument("--analysis-flags", help="Comma separated analysis flags to use",
                        type=lambda s: s.split(","), required=False, default=["-fsyntax-only"],
                        dest="analysis_flags")

    args, _ = parser.parse_known_args()

    if not Path(args.compile_commands).exists():
        print(f"[ERROR] File {args.compile_commands} do not exist")
        sys.exit(1)

    # Checked once, here: an override that cannot be run would otherwise fail per
    # translation unit, as a wall of exit-127 errors with no diagnostics in them.
    for flag, value in (("--cxx", args.cxx), ("--cc", args.cc)):
        if not value:
            continue
        words = shlex.split(value)
        if not words or shutil.which(words[0]) is None:
            print(f"[ERROR] {flag} is not runnable: {value!r}")
            sys.exit(1)
        
    ERRORS_CACHE_FOLDER.mkdir(parents=True, exist_ok=True)
    resolved_prefix = Path(args.path_prefix).resolve()

    state = load_or_initialize_state(args.no_cache)
    cmds = get_commands_of_interest(args.compile_commands, args.path_prefix, args.cxx, args.cc, args.analysis_flags)

    # One pool for the whole run: hashing, then compiling. Both are I/O bound and the
    # `with` is what guarantees the threads are joined even if the loop below raises.
    with ThreadPoolExecutor(max_workers=args.jobs) as executor:
        hash_sources(cmds, executor)
        header_hash_cache = prime_header_hashes(state, executor)

        # 1. Determine exactly what needs recompilation
        changed_files, unchanged_files, _ = get_needs_recompile(cmds, state, header_hash_cache)

        # 2. Dispatch tasks to thread pool
        futures = { **{executor.submit(run_cmd, cmds[f], resolved_prefix): f for f in changed_files},
                    **{executor.submit(read_cache, cmds[f], state.targets[f].header_deps): f for f in unchanged_files} }

        for future in as_completed(futures):
            file = futures[future]

            if file not in state.targets:
                state.targets[file] = TargetFile(set(), "", "")

            try:
                errors, file_deps = future.result()
                state.targets[file].header_deps = file_deps
                state.targets[file].content_hash = cmds[file].content_hash
                state.targets[file].path_hash = cmds[file].path_hash

                if errors:
                    print(''.join(errors).rstrip('\n'))
            except Exception as e:
                print(f"[ERROR] {e}", file=sys.stderr)

    # 3. Update cached dependencies & Save State
    if not args.no_cache:
        new_unique_deps = {}
        # Only preserve the dependencies actively used by the current targets
        for target in state.targets.values():
            for dep in target.header_deps:
                if dep not in new_unique_deps:
                    if dep not in header_hash_cache:
                        header_hash_cache[dep] = get_file_content_hash(dep)
                    new_unique_deps[dep] = header_hash_cache[dep]
                    
        state.unique_deps = new_unique_deps
        save_state(state)
